Adds Cyton wired work
atjohnson/brain-4ce pull request #5
Opened 2023-03-06 19:56 UTC by mgilmore42

Main component of this PR is to add in a streamlines variant (Cyton Wired) combining the work done on the Cyton Hat and OpenBCI's Cyton into a new novel design with greater hardware support. This design will allow for a single PCB configuration that supports both TIs ADS1299-X and ADS129X product lines on a single package.

This PR also brings in the main boards firmware as well as testing firmware that shows unique values being read form the ADC.

2023-03-06 22:23 UTC, atjohnson requested changes
- [ ] Rename [Daisy Functionality.kicad_sch](https://github.com/atjohnson/brain-4ce/blob/194cce391ea24f45ab58b976eebb81f25fc34c80/hardware/cyton%20hat/Daisy%20Functionality.kicad_sch) to "ADS129X-X functionality.kicad_sch"
- [ ] Check if any modifications need to be made to the original Cyton Hat design to accommodate the new Cyton

2023-03-06 22:41 UTC, atjohnson commented
Consider different placement of buttons to ease firmware programming in future revisions

2023-03-06 22:56 UTC, mitch-gilmore commented
The only difference I saw between the Cyton and the Daisy was with the CS and DRDY pins, but can you take a look and confirm this?

2023-03-07 00:04 UTC, atjohnson approved these changes

2023-03-07 00:05 UTC, merged